{"trial_id": "0002", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 10, "max_value": 50, "step": 5, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_value", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "rmsprop", "conditions": [], "values": ["rmsprop", "nadam", "adam"], "ordered": false}}], "values": {"units": 30, "dropout_value": 0.0, "optimizer": "nadam", "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 4, "tuner/round": 0}}, "metrics": {"metrics": {"accuracy": {"direction": "max", "observations": [{"value": [0.8532094359397888], "step": 1}]}, "loss": {"direction": "min", "observations": [{"value": [0.31464603543281555], "step": 1}]}, "precision": {"direction": "max", "observations": [{"value": [0.7306846976280212], "step": 1}]}, "recall": {"direction": "max", "observations": [{"value": [0.6151437759399414], "step": 1}]}, "val_accuracy": {"direction": "max", "observations": [{"value": [0.8580406904220581], "step": 1}]}, "val_loss": {"direction": "min", "observations": [{"value": [0.30135369300842285], "step": 1}]}, "val_precision": {"direction": "max", "observations": [{"value": [0.7679687738418579], "step": 1}]}, "val_recall": {"direction": "max", "observations": [{"value": [0.5698550939559937], "step": 1}]}}}, "score": 0.8580406904220581, "best_step": 1, "status": "COMPLETED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\reach\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\optree\\ops.py\", line 752, in tree_map\n    return treespec.unflatten(map(func, *flat_args))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: Invalid dtype: object\n"}